export const CompetencePrincipale = [
    "Developpement FRONT END",
    "Developpement BackEnd",
    "CSS",
    "HTML",
    "Javascript",
    "ReactJS",
    "Jquery",
    "NodeJS",
    "Redux",
    "Python",
    "Django",
    "DjangoRest",
    "Kivy",
    "MySQL",
    "PostgresSQL",
    "Oracle",
    "MongoDB",
    "Design Pattern",
    "Photoshop",
    "Illustrator",
    "Graphic design",
    "Brand design",
]